name: Publish Package to npm

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Format check
        run: yarn format

      - name: Lint code
        run: yarn lint

      - name: Run unit tests
        run: yarn test:unit

      - name: Build the package
        run: yarn build

      - name: Check if version already exists on npm
        id: version-check
        run: |
          if npm show stancer-clientjs@$(node -p "require('./package.json').version") > /dev/null 2>&1; then
            echo "Version already exists on npm. Skipping publish."
            exit 0
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        if: steps.version-check.outcome == 'success'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            This release includes the following changes:
            - See the [CHANGELOG](./CHANGELOG.md) for details.
          draft: false
          prerelease: false
