name: Sync Develop after Master Merge

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  sync-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Merge master into develop
        run: |
          git checkout develop
          git merge --no-ff origin/master -m "Merge master into develop"
          git push origin develop